
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && apt-get install -y \
    wget sudo git curl unzip \
    fp-compiler fpc-source \
    libpq-dev libmysqlclient-dev firebird-dev

RUN apt-get update && apt-get install -y \
    postgresql-client \
    mysql-client \
    firebird-dev \
    sqlite3 \
    libsqlite3-dev \
    dos2unix

# RUN echo -e "nameserver 208.67.222.22\nnameserver 8.8.4.4" | tee /etc/resolv.conf

RUN wget -qO /tmp/code-server.deb "https://github.com/coder/code-server/releases/download/v4.97.2/code-server_4.97.2_amd64.deb" && \
    apt-get install -y /tmp/code-server.deb && \
    rm /tmp/code-server.deb

RUN apt install -y git fpc libssl-dev

RUN apt install -y fp-utils

RUN wget -qO /tmp/libsagui.tar.gz https://github.com/risoflora/libsagui/releases/download/v3.5.2/libsagui_tls-3.5.2-linux_amd64.tar.gz
RUN mkdir -p /opt/libsagui
RUN tar -xvzf /tmp/libsagui.tar.gz -C /opt/libsagui --strip-components=1
RUN rm /tmp/libsagui.tar.gz
RUN echo "Contents of /opt/libsagui:" && ls -lah /opt/libsagui
RUN echo "Looking for libsagui.so.3..." && find /opt/libsagui -name "libsagui.so.3"
RUN cp $(find /opt/libsagui -name "libsagui.so.3") /usr/lib/
RUN ln -s /usr/lib/libsagui.so.3 /usr/lib/libsagui.so
RUN echo "Final /usr/lib contents:" && ls -lah /usr/lib/
RUN ldconfig

RUN ls -lah /usr/lib/libsagui.so.3 && \
    ldd /usr/lib/libsagui.so.3

RUN apt-get update && apt-get install -y \
    dnsutils \
    inetutils-ping \
    jq \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*


RUN useradd -m -s /bin/bash developer && \
    echo 'developer:devpassword' | chpasswd && \
    echo 'developer ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

WORKDIR /home/developer

EXPOSE 8080

USER developer

RUN mkdir -p .config/code-server
RUN chmod  -R 777 .config

COPY .env /usr/local/bin/.env

COPY entry-point.sh /usr/local/bin/entry-point.sh
RUN sudo chmod +x /usr/local/bin/entry-point.sh

# CMD [ "code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none", "/home/developer/Projects" ]
# CMD sudo chown -R developer:developer /home/developer/.config && \
#     code-server --bind-addr 0.0.0.0:8080 --auth none /home/developer/Projects --user-data-dir='/home/developer/Projects'

ENTRYPOINT ["/usr/local/bin/entry-point.sh"]