services:
  fpc-vscodium:
    build:
      context: .
      dockerfile: Dockerfile-fpc
    container_name: fpc-vscodium
    restart: unless-stopped
    ports:
      - "8123:8080"
      - "8321:8321"
    volumes:
      - ./Projects:/home/developer/Projects
      - ./config/vscodium:/home/developer/.config
      - ./config/fpc.cfg:/home/developer/.fpc.cfg
      - ./scripts:/home/developer/scripts
    environment:
      - DEBIAN_FRONTEND=noninteractive
  db:
    image: percona:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "6603:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/mysql-disable-ssl.cnf:/etc/mysql/conf.d/disable-ssl.cnf:ro
      - ./config/create-common-user.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=czyhnp
