services:
  fpc-vscodium:
    build:
      context: .
      dockerfile: Dockerfile-fpc
      args:
        TARGETARCH: ${TARGETARCH}
    platform: ${OS_PLATFORM}
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    container_name: fpc-vscodium
    restart: always
    ports:
      - "8123:8080"
      - "8321:8321"
      - "8322:8322"
      - "8323:8323"
      - "8324:8324"
      - "8325:8325"
      - "8326:8326"
      - "8327:8327"
      - "8328:8328"
      - "8329:8329"
      - "8330:8330"
      - "8331:8331"
    volumes:
      - ./Projects:/home/developer/Projects
      - ./config/vscodium:/home/developer/.config
      - ./config/fpc.cfg:/home/developer/.fpc.cfg
      - ./scripts:/home/developer/scripts
    environment:
      - DEBIAN_FRONTEND=noninteractive
  adminer:
    image: woahbase/alpine-adminer:x86_64
    container_name: adminer
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_DB=empresas_db      
  db:
    image: percona:8.0
    platform: ${DB_PLATFORM}
    container_name: db
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: always
    ports:
      - "6603:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/create-common-user.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./config/mysql-disable-ssl.cnf:/etc/mysql/conf.d/disable-ssl.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=czyhnp
  fb25:
    build:
      context: .
      dockerfile: Dockerfile-fb25
    platform: ${OS_PLATFORM}
    container_name: fb25
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: always
    ports:
      - "3051:3050"
    volumes:
      - ./data/fb25:/opt/firebird/2.5/data
    environment:
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=czyhnp
  fb30:
    build:
      context: .
      dockerfile: Dockerfile-fb30
    platform: ${OS_PLATFORM}
    container_name: fb30
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: always
    ports:
      - "3052:3050"
    volumes:
      - ./data/fb30:/opt/firebird/3.0/data
    environment:
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=czyhnp
  fb50:
    build:
      context: .
      dockerfile: Dockerfile-fb50
    platform: ${OS_PLATFORM}
    container_name: fb50
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: always
    ports:
      - "3053:3050"
    volumes:
      - ./data/fb50:/opt/firebird/5.0/data
    environment:
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=czyhnp

