SET SQL DIALECT 3;

SET NAMES UNICODE_FSS;

CREATE DATABASE '/opt/firebird/data/#(VERSION)/testdata.fdb'
USER 'SYSDBA' PASSWORD 'czyhnp'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UNICODE_FSS;

CREATE TABLE CUSTOMERS (
    CUST_ID       INTEGER NOT NULL,
    CUST_NAME     INTEGER,
    CUST_UNISITE  INTEGER
);

CREATE TABLE SMS_DETAIL (
    SD_ID                       INTEGER NOT NULL,
    SD_MESSAGE_DATA             VARCHAR(160)
);